[package]
name = "figma-image-tool"
version = "0.0.1"
edition = "2021"

[dependencies]
config = "0.15.8"
clap = { version = "4.4.11", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
serde = "1.0.217"
serde_json = "1.0"
