max_width = 100
tab_spaces = 2
edition = "2021"
newline_style = "Unix"
use_small_heuristics = "Default"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
format_code_in_doc_comments = true
